---
- name: check heroku Install
  shell: type heroku
  register: result
  ignore_errors: True

- name: heroku-cli install
  become: True
  shell: |
   curl -sL https://cdn.learnenough.com/heroku_install > /tmp/heroku_install
   source /tmp/heroku_install
  # when: result|failed
